### ISSUE TITLE
Email not being set

### ISSUE THREAD

**Issue by nlogachev** [SocialiteProviders/Twitch#1]
@DraperStudio Trying out this provider right now. The email property isn't being set. You've got it set to null in the mapUserToObject method and... that's all. Comparing to Laravel's default Socialite behaviour (e.g., Facebook), shouldn't you be checking:

```
'email' => isset($user['email']) ? $user['email'] : null
```

**Comment by nlogachev** [comment]
PR ready.

**Comment by DraperStudio** [comment]
Fix pushed https://github.com/SocialiteProviders/Twitch/commit/91daf025146f0bab44d3eea60181159a2906ba91 and v1.0.5 tagged
